apiVersion: v1
kind: Service
metadata:
  name: aurora-nexus
  labels:
    app: aurora-nexus
spec:
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: aurora-nexus
  type: ClusterIP
